### ISSUE TITLE
Steering Issue on Manual Control Mode

### ISSUE THREAD

**Issue by 929937690** [f1tenth/f1tenth_system#11]
I have a question about the steering control in Manual Control Mode. I am using a PS4 controller, but it is not from DualShock. I can mapping part correctly but on, but once I press the LB button, the steering will move toward the left, and I can't use the right joystick to control the steering. The left joystick used for speed works fine. 

I thought it was a configuration issue and tried to use the same joy_teleop config as the car works on ROS 1. I need help with it. Would you happen to have any insight on how I can fix this issue?

**Comment by hzheng40** [comment]
It's probably the mapping of the joystick axis to the teleop config. If you check [this yaml file](https://github.com/f1tenth/f1tenth_system/blob/7b4fa8f225055a3b7bab80515a432773ff36dea7/f1tenth_stack/config/joy_teleop.yaml#L29), you can see that a specific axis from the joy message is mapped to either speed or steering. So you can launch teleop again, then echo the `/joy` topic, move the joysticks around to see what axis is what index. Then change the yaml file accordingly.

**Comment by 929937690** [comment]
Thank you! It is fixed now!

**Comment by seegeert** [comment]
I have the same problem as the topic starter with a PS4 controller but can't get the mapping right.
If i change the mapping of the axis in the joy_teleop.yaml file the buttons on the controller still have the same function. Button L1 is the deathmans switch and if you press it the car steers to the left. If you press button L1 and L2 the car steers to te right. The left joystick works fine for speed.
The strange thing is that if I remap the drive speed axis, the left joystick is still for speed.
It looks like the program doesn't do anything with the changes that i make to the file.
After making changes to the file i relaunch teleop again.

Does anyone know what can be wrong or what i am possibly doing wrong?

Below is the config file:

joy:
  ros__parameters:
    # device_name: /dev/input/joypad-f710
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 5.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 5.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [5]
      message_value:
        data:
          value: 0
